name: HuHoBot
api: 5.0.0
main: HuHoBot\Main
author: Sunch233
version: 0.0.2

permissions:
  HuHo.command.bind:
    description: "HuHo Bot绑定群聊"
    default: op
commands:
  bind:
    permission: HuHo.command.bind
    description: "HuHo Bot绑定群聊"
    usage: /bind <code>